####### GET ALL PROPERTIES
GET http://localhost:3000/api/properties

###

###### GET A PROPERTY BY ID
GET http://localhost:3000/api/properties/63586fd638f4aa9596e2ffc


###

###### CREATE A PROPERTY
POST http://localhost:3000/api/properties
Content-Type: application/json

{
    "floor": 5,
    "letter": "B",
    "size": 120,
    "num_rooms": 5,
    "rented": false,
    "owner": "Maitane",
    "contact_email": "mai8@gmail.com"
}

# {
#     "floor": 2,
#     "letter": "A",
#     "size": 110,
#     "num_rooms": 4,
#     "rented": false,
#     "owner": "Maitane",
#     "contact_email": "maitane@gmail.com"
# }

###

####### UPDATE A PROPERTY
PUT http://localhost:3000/api/properties/63655aa06c0793215f18b8fc
Content-Type: application/json

{
    "rented": false
}

###

######## DELETE A PROPERTY BY ID
DELETE http://localhost:3000/api/properties/63655aa16c0793215f18b9


###

####### DELETE ALL PROPERTIES FROM ONE FLOOR
DELETE http://localhost:3000/api/properties/all/floor=9


###

###### GET A PROPERTY OF A OWNER
GET http://localhost:3000/api/properties/owner/lauri


###
